
image: docker:latest
services:
  - docker:dind

stages:
  - build

build:
  stage: build
  script:
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
    - docker build -t registry.gitlab.com/rvasily/golang-2017-2:$CI_COMMIT_REF_NAME 8/docker
    - docker push registry.gitlab.com/rvasily/golang-2017-2
  only:
    - tags
